name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Install dependencies on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          sudo yum update -y

          # Create and activate virtual environment
          if [ ! -d "venv" ]; then
            sudo yum install -y git python3 python3-venv
            python3 -m venv venv
          fi
          source venv/bin/activate

          # Install Poetry inside the virtual environment
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

          # Clone the repository inside the airflow/dags folder
          mkdir -p ~/airflow/dags
          git clone https://github.com/aakhavan/playground_datalake.git ~/airflow/dags/playground_datalake

          # Navigate to the project directory and install dependencies
          cd ~/airflow/dags/playground_datalake
          poetry install

          # Update Airflow configuration
          sed -i 's/\[core\]\/sql_alchemy_conn/\[database\]\/sql_alchemy_conn/' ~/airflow/airflow.cfg

          # Upgrade Airflow database
          echo "y" | airflow db upgrade
        EOF